pykeg/web/kegadmin/urls.py
from django.urls import path

from pykeg.plugin import util
from pykeg.web.kegadmin import views

urlpatterns = [
    # main page
    path(r"", views.dashboard, name="kegadmin-dashboard"),
    path("settings/general/", views.general_settings, name="kegadmin-main"),
    path("settings/location/", views.location_settings, name="kegadmin-location-settings"),
    path("settings/advanced/", views.advanced_settings, name="kegadmin-advanced-settings"),
    path("bugreport/", views.bugreport, name="kegadmin-bugreport"),
    path("export/", views.export, name="kegadmin-export"),
    path("beers/", views.beverages_list, name="kegadmin-beverages"),
    path("beers/add/", views.beverage_add, name="kegadmin-add-beverage"),
    path("beers/<int:beer_id>/", views.beverage_detail, name="kegadmin-edit-beverage"),
    path("devices/link/", views.link_device, name="kegadmin-link-device"),
    path("kegs/", views.keg_list, name="kegadmin-kegs"),
    path("kegs/online/", views.keg_list_online, name="kegadmin-kegs-online"),
    path("kegs/available/", views.keg_list_available, name="kegadmin-kegs-available"),
    path("kegs/kicked/", views.keg_list_kicked, name="kegadmin-kegs-kicked"),
    path("kegs/add/", views.keg_add, name="kegadmin-add-keg"),
    path("kegs/<int:keg_id>/", views.keg_detail, name="kegadmin-edit-keg"),
    path("brewers/", views.beverage_producer_list, name="kegadmin-beverage-producers"),
    path("brewers/add/", views.beverage_producer_add, name="kegadmin-add-beverage-producer"),
    path(
        "brewers/<int:brewer_id>/",
        views.beverage_producer_detail,
        name="kegadmin-edit-beverage-producer",
    ),
    path("controllers/", views.controller_list, name="kegadmin-controllers"),
    path("controllers/create/", views.add_controller, name="kegadmin-add-controller"),
    path(
        "controllers/<int:controller_id>/",
        views.controller_detail,
        name="kegadmin-edit-controller",
    ),
    path("taps/", views.tap_list, name="kegadmin-taps"),
    path("taps/create/", views.add_tap, name="kegadmin-add-tap"),
    path("taps/<int:tap_id>/", views.tap_detail, name="kegadmin-edit-tap"),
    path("users/", views.user_list, name="kegadmin-users"),
    path("users/<int:user_id>/", views.user_detail, name="kegadmin-edit-user"),
    path("drinks/", views.drink_list, name="kegadmin-drinks"),
    path("drinks/<int:drink_id>/", views.drink_edit, name="kegadmin-edit-drink"),
    path("tokens/", views.token_list, name="kegadmin-tokens"),
    path("tokens/create/", views.add_token, name="kegadmin-add-token"),
    path("tokens/<int:token_id>/", views.token_detail, name="kegadmin-edit-token"),
    path(
        "autocomplete/beverage/",
        views.autocomplete_beverage,
        name="kegadmin-autocomplete-beverage",
    ),
    path("autocomplete/user/", views.autocomplete_user, name="kegadmin-autocomplete-user"),
    path("autocomplete/token/", views.autocomplete_token, name="kegadmin-autocomplete-token"),
    path("plugin/<str:plugin_name>/", views.plugin_settings, name="kegadmin-plugin-settings"),
    path("email/", views.email, name="kegadmin-email"),
    path("logs/", views.logs, name="kegadmin-logs"),
    path("users/create/", views.add_user, name="kegadmin-add-user"),
]

if util.get_plugins():
    urlpatterns += util.get_admin_urls()

pykeg/web/kegadmin/forms.py
from builtins import object, str

from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Field, Layout, Submit
from django import forms
from django.contrib.humanize.templatetags.humanize import naturaltime

from pykeg.core import keg_sizes, models
from pykeg.util import units

ALL_TAPS = models.KegTap.objects.all()
ALL_KEGS = models.Keg.objects.all()
ALL_METERS = models.FlowMeter.objects.all()
ALL_TOGGLES = models.FlowToggle.objects.all()
ALL_THERMOS = models.ThermoSensor.objects.all()


class ChangeKegForm(forms.Form):
    keg_size = forms.ChoiceField(
        choices=keg_sizes.CHOICES, initial=keg_sizes.HALF_BARREL, required=True
    )

    initial_volume = forms.FloatField(
        label="Initial Volume", initial=0.0, required=False, help_text="Keg's Initial Volume"
    )

    beer_name = forms.CharField(required=False)  # legacy
    brewer_name = forms.CharField(required=False)  # legacy

    beverage_name = forms.CharField(label="Beer Name", required=False)
    beverage_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    producer_name = forms.CharField(label="Brewer", required=False)
    producer_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    style_name = forms.CharField(
        required=True, label="Style", help_text="Example: Pale Ale, Stout, etc."
    )

    helper = FormHelper()
    helper.form_class = "form-horizontal beer-select"
    helper.layout = Layout(
        Field("beverage_name", css_class="input-xlarge"),
        Field("beverage_id", type="hidden"),
        Field("producer_name", css_class="input-xlarge"),
        Field("producer_id", type="hidden"),
        Field("style_name", css_class="input-xlarge"),
        Field("keg_size", css_class="input-xlarge"),
        Field("initial_volume", css_class="input-volume"),
        FormActions(
            Submit("submit_change_keg_form", "Activate Keg", css_class="btn-primary"),
        ),
    )

    def clean_beverage_name(self):
        beverage_name = self.cleaned_data.get("beverage_name")
        if not beverage_name:
            beverage_name = self.cleaned_data.get("beer_name")
            if not beverage_name:
                raise forms.ValidationError("Must specify a beverage name")
            self.cleaned_data["beverage_name"] = beverage_name
        return beverage_name

    def clean_producer_name(self):
        producer_name = self.cleaned_data.get("producer_name")
        if not producer_name:
            producer_name = self.cleaned_data.get("brewer_name")
            if not producer_name:
                raise forms.ValidationError("Must specify a producer name")
            self.cleaned_data["producer_name"] = producer_name
        return producer_name

    def save(self, tap):
        if not self.is_valid():
            raise ValueError("Form is not valid.")

        if tap.is_active():
            tap.end_current_keg()

        keg_size = self.cleaned_data.get("keg_size")
        full_volume_ml = self.cleaned_data.get("full_volume_ml")

        if keg_size != "other":
            full_volume_ml = None
        else:
            full_volume_ml = self.cleaned_data.get("initial_volume")

        # TODO(mikey): Support non-beer beverage types.
        cd = self.cleaned_data
        keg = models.Keg.start_keg(
            tap,
            beverage_name=cd["beverage_name"],
            producer_name=cd["producer_name"],
            beverage_type="beer",
            style_name=cd["style_name"],
            keg_type=cd["keg_size"],
            full_volume_ml=full_volume_ml,
        )

        if cd.get("description"):
            keg.description = cd["description"]
            keg.save()


class EndKegForm(forms.Form):
    keg = forms.ModelChoiceField(queryset=ALL_KEGS, widget=forms.HiddenInput)

    helper = FormHelper()
    helper.form_class = "form-horizontal beer-select"
    helper.layout = Layout(
        Field("keg", type="hidden"),
        FormActions(
            Submit("submit_end_keg_form", "End Keg", css_class="btn-danger"),
        ),
    )


class TapForm(forms.ModelForm):
    class FlowMeterModelChoiceField(forms.ModelChoiceField):
        def label_from_instance(self, meter):
            if meter.tap:
                return "{} (connected to {})".format(meter, meter.tap.name)
            else:
                return str(meter)

    class FlowToggleModelChoiceField(forms.ModelChoiceField):
        def label_from_instance(self, toggle):
            if toggle.tap:
                return "{} (connected to {})".format(toggle, toggle.tap.name)
            else:
                return str(toggle)

    class ThermoSensorModelChoiceField(forms.ModelChoiceField):
        def label_from_instance(self, sensor):
            last_log = sensor.LastLog()
            if last_log:
                return "{} (Last report: {})".format(sensor, naturaltime(last_log.time))
            else:
                return str(sensor)

    meter = FlowMeterModelChoiceField(
        queryset=ALL_METERS,
        required=False,
        empty_label="Not connected.",
        help_text="Tap is routed thorough this flow meter. If unset, reporting is disabled.",
    )

    toggle = FlowToggleModelChoiceField(
        queryset=ALL_TOGGLES,
        required=False,
        empty_label="Not connected.",
        help_text="Optional flow toggle (usually a relay/valve) connected to this tap.",
    )

    temperature_sensor = ThermoSensorModelChoiceField(
        queryset=ALL_THERMOS,
        required=False,
        empty_label="No sensor.",
        help_text="Optional sensor monitoring the temperature at this tap.",
    )

    class Meta(object):
        model = models.KegTap
        fields = ("name", "notes", "temperature_sensor", "sort_order")

    def __init__(self, *args, **kwargs):
        super(TapForm, self).__init__(*args, **kwargs)

        if self.instance:
            self.fields["meter"].initial = self.instance.current_meter()
            self.fields["toggle"].initial = self.instance.current_toggle()
            self.fields["temperature_sensor"].initial = self.instance.temperature_sensor

    def save(self, commit=True):
        if not commit:
            raise ValueError("TapForm does not support commit=False")
        tap = super(TapForm, self).save(commit=True)
        tap.connect_meter(self.cleaned_data["meter"])
        tap.connect_toggle(self.cleaned_data["toggle"])
        return tap

    helper = FormHelper()
    helper.form_class = "form-horizontal"
    helper.layout = Layout(
        Field("name", css_class="input-xlarge"),
        Field("meter", css_class="input-xlarge"),
        Field("toggle", css_class="input-xlarge"),
        Field("temperature_sensor", css_class="input-xlarge"),
        Field("sort_order", css_class="input-xlarge"),
        Field("notes", css_class="input-block-level", rows="3"),
        FormActions(
            Submit("submit_tap_form", "Save Settings", css_class="btn-success"),
        ),
    )


class DeleteTapForm(forms.Form):
    helper = FormHelper()
    helper.form_class = "form-horizontal"
    helper.layout = Layout(
        FormActions(
            Submit("submit_delete_tap_form", "Delete Tap", css_class="btn-danger"),
        )
    )


class KegForm(forms.Form):
    keg_size = forms.ChoiceField(
        choices=keg_sizes.CHOICES, initial=keg_sizes.HALF_BARREL, required=True
    )

    initial_volume = forms.FloatField(
        label="Initial Volume", initial=0.0, required=False, help_text="Keg's Initial Volume"
    )

    beer_name = forms.CharField(required=False)  # legacy
    brewer_name = forms.CharField(required=False)  # legacy

    beverage_name = forms.CharField(label="Beer Name", required=False)
    beverage_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    producer_name = forms.CharField(label="Brewer", required=False)
    producer_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    style_name = forms.CharField(
        required=True, label="Style", help_text="Example: Pale Ale, Stout, etc."
    )

    description = forms.CharField(
        max_length=256,
        label="Description",
        widget=forms.Textarea(),
        required=False,
        help_text="Optional user-visible description of the keg.",
    )
    notes = forms.CharField(
        label="Notes",
        required=False,
        widget=forms.Textarea(),
        help_text="Optional private notes about this keg, viewable only by admins.",
    )
    connect_to = forms.ModelChoiceField(
        queryset=ALL_TAPS,
        label="Connect To",
        required=False,
        help_text="If selected, immediately activates the keg on this tap. "
        "(Any existing keg will be ended.)",
    )

    helper = FormHelper()
    helper.form_class = "form-horizontal beer-select"
    helper.layout = Layout(
        Field("beverage_name", css_class="input-xlarge"),
        Field("beverage_id", type="hidden"),
        Field("producer_name", css_class="input-xlarge"),
        Field("producer_id", type="hidden"),
        Field("style_name", css_class="input-xlarge"),
        Field("keg_size", css_class="input-xlarge"),
        Field("initial_volume", css_class="input-volume"),
        Field("description", css_class="input-block-level", rows="3"),
        Field("notes", css_class="input-block-level", rows="3"),
        Field("connect_to", css_class="input-block-level"),
        FormActions(
            Submit("submit_add_keg", "Save", css_class="btn-primary"),
        ),
    )

    def clean_beverage_name(self):
        beverage_name = self.cleaned_data.get("beverage_name")
        if not beverage_name:
            beverage_name = self.cleaned_data.get("beer_name")
            if not beverage_name:
                raise forms.ValidationError("Must specify a beverage name")
            self.cleaned_data["beverage_name"] = beverage_name
        return beverage_name

    def clean_producer_name(self):

pykeg/web/kegadmin/templates/kegadmin/add_tap.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Add Tap | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Add Tap{% endblock %}

{% block kegadmin-main %}
{% crispy form %}
{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/add_token.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Add Token | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Add Token{% endblock %}

{% block kegadmin-main %}
{% crispy form %}
{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/backup_export.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Backup/Export | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Backup/Export{% endblock %}

{% block kegadmin-main %}

<h3>Create a Backup</h3>
<p>
  <b>Experimental.</b> Click "Export" to generate a zipfile containing all
  media and database records.
</p>
<form action="" method="POST">{% csrf_token %}
  <button class="btn btn-info" name="package_backup" type="submit">
    Export
  </button>
</form>

{% if backups %}
<h3>Saved Backups</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Server</th>
      <th>Version</th>
      <th>Size</th>
      <th>Created</th>
      <th>Download</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for backup in backups %}
    <tr>
      <td>{{ backup.server_name }}</td>
      <td>{{ backup.server_version }}</td>
      <td>
        {{ backup.size_bytes|filesizeformat }}
        ({{ backup.num_tables }} tables, {{ backup.num_media_files }} media files)</td>
      <td>{% timeago backup.created_time %}</td>
      <td>
        <a class="btn btn-success" href="{{ backup.url }}">
          Download
        </a>
      </td>
      <td>
        <form action="" method="POST">{% csrf_token %}
          <input type="hidden" name="backup_name" value="{{ backup.backup_name }}">
          <button class="btn btn-danger" name="delete_backup" type="submit">
            Delete
          </button>
        </form>
      </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/beer_type_detail.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Edit Beer | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Edit Beer {% endblock %}

{% block kegadmin-main %}

<h2>Edit Beer</h2>

{% if beer_type.picture %}
<div class="row">
    <div class="col-md-10">
        <p><img class="img-responsive" src="{{beer_type.picture.resized.url}}"/></p>
    </div>
</div>
{% endif %}

{% crispy form %}

{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/brewer_add.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Add Brewer | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Add Brewer {% endblock %}

{% block kegadmin-main %}

<h2>Add Brewer</h2>

{% if brewer.picture %}
<div class="row">
    <div class="col-md-10">
        <p><img class="img-responsive" src="{{brewer.picture.resized.url}}"/></p>
    </div>
</div>
{% endif %}

{% crispy form %}

{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/controller_detail.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Edit Controller: {{ controller.name }} | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Edit Controller: {{ controller.name }}{% endblock %}

{% block kegadmin-main %}

<h3>{{ controller.name }} <small>{{ controller.type }}</small></h3>
<ul class="nav nav-tabs" id="controllerDetails">
  <li><a href="#1" data-toggle="tab">About</a></li>
  <li><a href="#2" data-toggle="tab">Flow Meters</a></li>
  <li><a href="#3" data-toggle="tab">Flow Toggles</a></li>
  <li><a href="#4" data-toggle="tab">Controller Settings</a></li>
  <li><a href="#deleteModal" data-toggle="modal">Delete Controller</a></li>
</ul>

<div class="row">
  <div class="col-md-12">
    <div class="tab-content">
      <div class="tab-pane" id="1">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td>Name</td>
              <td>{{ controller.name }}</td>
            </tr>
            <tr>
              <td>Model Name</td>
              <td>{{ controller.model_name }}</td>
            </tr>
            <tr>
              <td>Serial Number</td>
              <td>{{ controller.serial_number }}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="2">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Ticks per mL</th>
            </tr>
          </thead>
          <tbody>
            {% if controller.meters.all %}
            {% for meter in controller.meters.all %}
            <tr>
              <td>
                <a class="btn btn-sm btn-primary" href="#editFlowMeterModal{{ meter.id }}"
                  data-toggle="modal">Edit</a>&nbsp;&nbsp;
                <span>{{ meter }}</span>
              </td>
              <td>
                {{ meter.ticks_per_ml }}
              </td>
            </tr>
            {% endfor %}
            {% endif %}
            <tr class="info">
              <td colspan="2" style="text-align:right;">
                <a class="btn btn-sm btn-success pull-right" href="#addFlowMeterModal" data-toggle="modal"><i
                    class="glyphicon glyphicon-plus"></i> Add Flow Meter</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="3">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            {% if controller.toggles.all %}
            {% for toggle in controller.toggles.all %}
            <tr>
              <td>
                <a class="btn btn-sm btn-primary" href="#editFlowToggleModal{{ toggle.id }}"
                  data-toggle="modal">Edit</a>&nbsp;&nbsp;
                <span>{{ toggle }}</span>
              </td>
            </tr>
            {% endfor %}
            {% endif %}
            <tr class="info">
              <td style="text-align:right;">
                <a class="btn btn-sm btn-success pull-right" href="#addFlowToggleModal" data-toggle="modal"><i
                    class="glyphicon glyphicon-plus"></i> Add Flow Toggle</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="4">
          {% crispy controller_settings_form %}
        </div>

    </div>
  </div>
</div>

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="deleteDialogLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="deleteDialogLabel">Delete Controller: {{ controller.name }}?</h3>
      </div>
      <div class="modal-body">
        <p>
          Are you sure you want to delete <b>Controller: {{ controller.name }}</b>?
        </p>
        {% crispy delete_controller_form %}
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="addFlowMeterModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addFlowMeterDialogLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="addFlowMeterDialogLabel">Add Flow Meter to Controller: {{ controller.name }}</h3>
      </div>
      <div class="modal-body">
        {% crispy add_flow_meter_form %}
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="addFlowToggleModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addFlowToggleDialogLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="addFlowToggleDialogLabel">Add Flow Toggle to Controller: {{ controller.name }}</h3>
      </div>
      <div class="modal-body">
        {% crispy add_flow_toggle_form %}
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
  </div>
</div>

{% if controller.meters.all %}
{% for meter in controller.meters.all %}
<div id="editFlowMeterModal{{ meter.id }}" class="modal fade" tabindex="-1" role="dialog"
  aria-labelledby="editFlowMeterDialogLabel{{ meter.id }}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <form class="modal-content form-horizontal" action="" method="POST">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h3 id="editFlowMeterDialogLabel{{ meter.id }}">Edit {{ meter }} or </h3>
        <!-- <form action="" method="POST" style="display:inline;">
                    <input type="hidden" name="flowmeter_id" value="{{ meter.id }}">
                    <input class="btn btn-danger" name="delete_flow_meter" type="submit" value="Delete">
                    {% csrf_token %}
                </form> -->
      </div>
      <div class="modal-body">
        <div id="div_id_port_name{{ meter.id }}" class="form-group">
          <label for="id_port_name{{ meter.id }}" class="control-label requiredField col-sm-2">
            Port Name<span class="asteriskField">*</span></label>
          <div class="col-sm-10">
            <input class="form-control textinput textInput" type="text" name="port_name" id="id_port_name{{ meter.id }}"
              value="{{ meter.port_name }}">
            <p id="hint_id_port_name{{ meter.id }}" class="help-block">Controller-specific data port name for this
              meter.</p>
          </div>
        </div>
        <div id="div_id_ticks_per_ml{{ meter.id }}" class="form-group">
          <label for="id_ticks_per_ml{{ meter.id }}" class="control-label requiredField col-sm-2">
            Ticks per mL<span class="asteriskField">*</span></label>
          <div class="col-sm-10">
            <input class="form-control textinput textInput" type="text" name="ticks_per_ml"
              id="id_ticks_per_ml{{ meter.id }}" value="{{ meter.ticks_per_ml }}">
            <p id="hint_id_ticks_per_ml{{ meter.id }}" class="help-block">Flow meter pulses per mL of fluid. Common
              values: 2.724 (FT330-RJ), 5.4 (SF800)</p>
          </div>
        </div>
        <input type="hidden" name="flowmeter_id" value="{{ meter.id }}">
      </div>
      <div class="modal-footer">
        <input class="btn btn-primary" name="edit_flow_meter" type="submit" value="Update Flow Meter">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
      {% csrf_token %}
    </form>
  </div>
</div>
{% endfor %}
{% endif %}

{% if controller.toggles.all %}
{% for meter in controller.toggles.all %}
<div id="editFlowToggleModal{{ toggle.id }}" class="modal fade" tabindex="-1" role="dialog"
  aria-labelledby="editFlowToggleDialogLabel{{ toggle.id }}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <form class="modal-content form-horizontal" action="" method="POST">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h3 id="editFlowToggleDialogLabel{{ toggle.id }}">Edit {{ toggle }} or </h3>
        <!-- <form action="" method="POST" style="display:inline;">
                    <input type="hidden" name="flowtoggle_id" value="{{ toggle.id }}">
                    <input class="btn btn-danger" name="delete_flow_toggle" type="submit" value="Delete">
                    {% csrf_token %}
                </form> -->
      </div>
      <div class="modal-body">
        <div id="div_id_port_name{{ toggle.id }}" class="form-group">
          <label for="id_port_name{{ toggle.id }}" class="control-label requiredField col-sm-2">
            Port Name<span class="asteriskField">*</span></label>
          <div class="col-sm-10">
            <input class="form-control textinput textInput" type="text" name="port_name"
              id="id_port_name{{ toggle.id }}" value="{{ toggle.port_name }}">
            <p id="hint_id_port_name{{ toggle.id }}" class="help-block">Controller-specific data port name for this
              toggle.</p>
          </div>
        </div>
        <input type="hidden" name="flowtoggle_id" value="{{ toggle.id }}">
      </div>
      <div class="modal-footer">
        <input class="btn btn-primary" name="edit_flow_toggle" type="submit" value="Update Flow Toggle">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
      {% csrf_token %}
    </form>
  </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}

{% block kb-extrajs %}
<script>
  $(document).ready(function () {
    $('#controllerDetails a:first').tab('show');
  });

</script>
{% endblock %}

pykeg/web/kegadmin/templates/kegadmin/keg_add.html
{% extends "kegadmin/base.html" %}
{% load kegweblib %}
{% load crispy_forms_tags %}

{% block title %}Kegbot Admin: Add Keg | {{ block.super }}{% endblock %}
{% block pagetitle %}Kegbot Admin: Add Keg {% endblock %}

{% block kegadmin-main %}

{% include 'kegadmin/includes/keg_nav.html' %}

{% crispy form %}

{% endblock %}

{% block kb-extrajs %}
<script>

$(document).ready(function() {
  $('#div_id_initial_volume').hide();

  $('#id_keg_size').change(function() {
    var choice = $(this).val();
    if (choice == 'other') {
      $('#div_id_initial_volume').fadeIn();
    } else {
      $('#div_id_initial_volume').fadeOut();
    }
  });
});

</script>
{% endblock %}